name: f151
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  cloud_firestore: ^4.8.0
  device_info_plus: ^9.0.2
  firebase_auth: ^4.6.2
  firebase_auth_web: ^5.5.3
  firebase_core: ^2.13.1
  firebase_storage: ^11.2.3
  flutter:
    sdk: flutter
  flutter_animate: ^4.1.1+1
  flutter_bloc: ^8.1.3
  image_picker: ^0.8.9
  intl: ^0.18.1
  material_design_icons_flutter: ^7.0.7296
  onesignal_flutter: ^3.5.1
  shared_preferences: ^2.1.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/categories/
    - assets/images/logo/
